- single-line-diagram-viewer/.gitignore
- single-line-diagram-viewer/LICENSE
- single-line-diagram-viewer/pom.xml
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/AbstractContainerDiagramView.java
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/DLExporter.java
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/DisplayVoltageLevel.java
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/MouseClickNotDragDetector.java
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/NodeHandler.java
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SubstationDiagramView.java
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SwitchPositionChangeListener.java
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/VoltageLevelDiagramView.java
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/VoltageLevelHandler.java
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/WireHandler.java
- single-line-diagram-viewer/src/main/resources/log4j2.xml
- single-line-diagram-viewer/src/main/resources/logback.xml
- single-line-diagram-viewer/src/test/java/com/powsybl/sld/viewer/WireHandlerTest.java
Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>
(if any of the questions/checkboxes don't apply, please delete them entirely)
> SLD viewer

- single-line-diagram-viewer/pom.xml
No
Lib updates
powsybl-single-line-diagram 2.1.0-SNAPSHOT and powsybl-core 4.0.1
powsybl-single-line-diagram 2.2.0-SNAPSHOT and powsybl-core 4.1.0
No
> Update powsybl-core and powsybl-single-line-diagram

- single-line-diagram-viewer/pom.xml
No
Lib updates
powsybl-single-line-diagram 2.2.0-SNAPSHOT and powsybl-core 4.1.0
powsybl-single-line-diagram 2.3.0-SNAPSHOT and powsybl-core 4.2.0
No
> Bump 4.2.0 core & 2.3.0-SNAPSHOT sld

- single-line-diagram-viewer/pom.xml
No
Lib updates
powsybl-single-line-diagram 2.3.0-SNAPSHOT and powsybl-core 4.2.0
powsybl-single-line-diagram 2.4.0-SNAPSHOT and powsybl-core 4.3.1
No
> Bump 4.3.1 core & 2.4.0-SNAPSHOT sld

- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/NodeHandler.java
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/VoltageLevelHandler.java
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/WireHandler.java
No
Update following powsybl/powsybl-single-line-diagram#249
Does not support changes of mentionned PR
Supports changes of mentionned PR
No
> Adapt code to Point snakelines

- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/AbstractContainerDiagramView.java
No
Bug fix
ClassCastException when installing wire handlers
Wire handlers installed with no exception
No
> Fix ClassCastException on wire handler

- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
No
Feature
Quickly testing all substations in a file is tedious as all voltage levels are listed
Button hide voltage levels added
No
> Add hide voltage levels button

- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/AbstractContainerDiagramView.java
**Please check if the PR fulfills these requirements** 
No
Bug fix
Unzooming is very slow
Unzooming behaves like in similar application
No
> Fix very slow unzoom

- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/NodeHandler.java
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/VoltageLevelHandler.java
No
Update
Not supporting changes of powsybl/powsybl-single-line-diagram#270
Supporting changes of powsybl/powsybl-single-line-diagram#270
> Adapt to svg size changes

- single-line-diagram-viewer/pom.xml
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
No
Lib updates
powsybl-single-line-diagram 2.4.0-SNAPSHOT and powsybl-core 4.3.1
powsybl-single-line-diagram 2.5.0-SNAPSHOT and powsybl-core 4.4.0
No
> Bump 4.4.0 core & 2.5.0-SNAPSHOT sld

- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
No
Feature
Cannot set label diagonal, changing the angle has no effect
If checkbox ticked, the angle is applied
No
> Add label diagonal checkbox

- README.md
Signed-off-by: HARPER Jon <jon.harper87@gmail.com>
NO
feature
default git branch is master
default git branch is main
NO
> switch git branch master to main

- single-line-diagram-viewer/pom.xml
No
Lib updates
powsybl-single-line-diagram 2.5.0-SNAPSHOT and powsybl-core 4.4.0
powsybl-single-line-diagram 2.6.0-SNAPSHOT and powsybl-core 4.5.1
No
> Bump powsybl-core to 4.5.1 & powsybl-single-line-diagram to 2.6.0-SNAPSHOT

- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
**Please check if the PR fulfills these requirements** 
No
Feature
When choosing file, the initial folder is always reset to target folder
When choosing file, the initial folder is the one where the previous file was
**Does this PR introduce a breaking change or deprecate an API?** No
> Save data folder

- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/JsHandler.java
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
- single-line-diagram-viewer/src/main/resources/svg.html
- single-line-diagram-viewer/src/main/resources/svg.js
Fixes #027 
Fixes #028 
Feature
We cannot interact with svg on webview
We can operate switch and navigate between diagram on webview
(if any of the questions/checkboxes don't …
> Add callback to operate switches

- single-line-diagram-viewer/pom.xml
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
Fixes #30 
(if any of the questions/checkboxes don't apply, please delete them entirely)
> Update code to new SingleLineDiagram API

- single-line-diagram-viewer/pom.xml
No
Lib updates
powsybl-single-line-diagram 2.7.0-SNAPSHOT and powsybl-core 4.6.0-RC1
powsybl-single-line-diagram 2.8.0-SNAPSHOT and powsybl-core 4.6.0
No
> Bump 4.6.0 core & 2.8.0-SNAPSHOT sld

- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
…iagram
Signed-off-by: Thomas ADAM <tadam@silicom.fr>
No
Feature
Compilation failed
LayoutParameters are updated as issue 303 from powsybl-single-line-diagram
(if any of the …
> Update from issue 303 (powsybl-single-line-diagram)

- .gitignore
- single-line-diagram-viewer/pom.xml
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@gmail.com>
#37 
Bug fix
(if any of the questions/checkboxes don't apply, please delete them entirely)
> Upgrade to SLD 2.9.0-SNAPSHOT

- single-line-diagram-viewer/pom.xml
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
No
Lib updates
powsybl-single-line-diagram 2.9.0-SNAPSHOT
powsybl-single-line-diagram 2.10.0-SNAPSHOT
No
> Upgrade to SLD 2.10.0-SNAPSHOT

- .github/workflows/maven.yml
- network-area-diagram-viewer/pom.xml
No
Feature
No sonar cloud analysis / checkstyle
Sonar cloud analysis / checkstyle
No
There was no workflow included so far as this repo is for development use only, but having a sonar cloud & checkstyle analysis allows to keep a code quality
> Add workflow

- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
No
Feature
Voltage levels with no substation do not appear in the list of voltage levels
Voltage levels with no substation are in the list of voltage levels
No
> Add voltage levels without substation in the list

- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
**Does this PR already have an issue describing the problem ?** No
**What kind of change does this PR introduce?** Bug fix
**What is the current behavior?** When SVG is small enough to fit entirely in the webview, zooming in does not change the variables and therefore does not let the user use the button Fit To Content even though it should.
**What is the new behavior (if this is a feature change)?** The button Fit To Content always works properly.
**Does this PR introduce a breaking change or deprecate an API?** No
> Fix Fit To Content

- README.md
- single-line-diagram-viewer/pom.xml
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
No
Feature
Viewer needs to be launched from IDE, or with verbose command, both with specific VM arguments. 
Viewer can be launched using javafx maven plugin: `mvn javafx:run`
> Launch viewer from command line

- single-line-diagram-viewer/pom.xml
- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
No
Libs update
powsybl-single-line-diagram 2.11.0-SNAPSHOT, powsybl-core 4.8.0, javafx 17.0.1
powsybl-single-line-diagram 2.14.0-SNAPSHOT, powsybl-core 4.10.1, javafx 19
No
> Update to latest powsybl-single-line-diagram SNAPSHOT version

- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
No
Bug fix / feature
- Search case sensitive
- Voltage levels with empty substation not filtered out with search field
- Search case insensitive
- Voltage levels with empty substation also filtered out with search field
No
> Search filter fixes

- network-area-diagram-viewer/src/main/java/com/powsybl/nad/viewer/controller/MainViewController.java
- network-area-diagram-viewer/src/main/java/com/powsybl/nad/viewer/controller/Model.java
- network-area-diagram-viewer/src/main/resources/mainView.fxml
No
Feature
LayoutParameters cannot be changed
LayoutParameters.textNodesForceLayout can be changed with a checkbox
> Add layout parameter checkbox to include TextNodes in layout algorithm

- .github/workflows/maven.yml
No
Workflow changes
Workflow: build on ubuntu, windows, macos
Workflow: build only on ubuntu (no unit test, workflow mainly meant for launching sonar cloud analysis)
> Workflow for nad-viewer only on ubuntu

- network-area-diagram-viewer/src/main/java/com/powsybl/nad/viewer/controller/MainViewController.java
- network-area-diagram-viewer/src/main/java/com/powsybl/nad/viewer/controller/Model.java
- network-area-diagram-viewer/src/main/resources/mainView.fxml
No
Feature
Spring repulsion factor cannot be set
Spring repulsion factor can be set thanks to a spinner
> [nad-viewer] Add spring repulsion factor spinner

- network-area-diagram-viewer/pom.xml
- network-area-diagram-viewer/src/main/java/com/powsybl/nad/viewer/MainViewController.java
- network-area-diagram-viewer/src/main/java/com/powsybl/nad/viewer/Model.java
- network-area-diagram-viewer/src/main/resources/mainView.fxml
Feature
Allow the user to modify some of the SVG parameters (insert `desc` elements, use ids for labels, display substation).
> Network Area Diagrams: add SVG parameters

- network-area-diagram-viewer/src/main/java/com/powsybl/nad/viewer/EnumChoiceBox.java
- network-area-diagram-viewer/src/main/java/com/powsybl/nad/viewer/MainViewController.java
- network-area-diagram-viewer/src/main/java/com/powsybl/nad/viewer/Model.java
- network-area-diagram-viewer/src/main/resources/mainView.fxml
Feature
Allow the user configure SVG parameters related to diagram size.
> SVG parameters related to diagram size

- .github/workflows/maven.yml
- network-area-diagram-viewer/pom.xml
- network-area-diagram-viewer/src/main/java/com/powsybl/nad/viewer/DiagramController.java
- network-area-diagram-viewer/src/main/java/com/powsybl/nad/viewer/MainViewController.java
- network-area-diagram-viewer/src/main/java/com/powsybl/nad/viewer/Model.java
- network-area-diagram-viewer/src/main/resources/mainView.fxml
No
Feature
Viewer based on nad 0.7.0-SNAPSHOT
Viewer based on nad 3.1.0-SNAPSHOT
> Update viewer following powsybl-diagram 3.0.0 release

- power-factory-viewer/pom.xml
- power-factory-viewer/src/main/java/com/powsybl/powerfactory/viewer/DataAttributeTable.java
- power-factory-viewer/src/main/java/com/powsybl/powerfactory/viewer/DataObjectTree.java
Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@gmail.com>
(if any of the questions/checkboxes don't apply, please delete them entirely)
> Add search bar

- network-area-diagram-viewer/pom.xml
- power-factory-viewer/pom.xml
- single-line-diagram-viewer/pom.xml
Signed-off-by: Sophie Frasnedo <sophie.frasnedo@rte-france.com>
update versions of powsybl-core and powsybl-diagram in pom files
> update powsybl-core and powsybl-diagram versions in pom files

- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
No
Bug fix
Following powsybl-diagram 3.1.0 release, the topologyStyleProvider is increasing the style counter when reused for another diagram
The topologyStyleProvider is renewed when drawing another diagram
No
> [sld-viewer] Update styleProviders before redrawing

- single-line-diagram-viewer/src/main/java/com/powsybl/sld/viewer/SingleLineDiagramViewer.java
No
Bug fix
Layout parameters changes are not taken into account
Layout parameters changes are taken into account
(if any of the questions/checkboxes don't apply, please delete …
> Layout parameters changes are not taken into account

- diagram-viewer/pom.xml
No
Dependency update / bug fix
powsybl-dependency 2023.3.0, position layout parameters not linked to javafx invisible checkboxes
powsybl-dependency 2024.0.0, adapted to new position layout parameters API, and fix the corresponding bugs at the same time
> Bump powsybl-dependencies to 2024.0.0

- diagram-viewer/src/main/java/com/powsybl/diagram/viewer/MainViewController.java
- diagram-viewer/src/main/resources/mainView.fxml
> Issue 88 - Add IdentifiableType filter

- diagram-viewer/src/main/java/com/powsybl/diagram/viewer/MainViewController.java
No
Bug fix / feature
Phase-shift transformer is missing in component types filter
HvdcLines / TieLines / DanglingLines filter not working properly / not working
Phase-shift transformer is in component types filter
HvdcLines / TieLines / DanglingLines filter fixed thanks to an enum refactor
> Fix component type filter and add new filter types

- README.md
- diagram-viewer/src/main/resources/areaView.fxml
- diagram-viewer/src/main/resources/mainView.fxml
- diagram-viewer/src/main/resources/nad/networkAreaDiagramView.fxml
- diagram-viewer/src/main/resources/nad/view.fxml
- diagram-viewer/src/main/resources/sld/singleLineDiagramView.fxml
- diagram-viewer/src/main/resources/sld/view.fxml
No
Lib update
JavaFX 17.0.1
JavaFX 21.0.2
> Update to JavaFX 21.0.2

- diagram-viewer/src/main/java/com/powsybl/diagram/viewer/MainViewController.java
> Cancel previous network loading service

- diagram-viewer/src/main/java/com/powsybl/diagram/viewer/nad/LayoutParametersBean.java
- diagram-viewer/src/main/java/com/powsybl/diagram/viewer/nad/NetworkAreaDiagramModel.java
- diagram-viewer/src/main/java/com/powsybl/diagram/viewer/nad/NetworkAreaDiagramViewController.java
- diagram-viewer/src/main/resources/nad/view.fxml
No
Feature
Number max of steps is fixed
Number max of steps is set thanks to spinner
> Add spinner for NAD number of steps layoutParameter

- diagram-viewer/pom.xml
- diagram-viewer/src/main/java/com/powsybl/diagram/viewer/MainViewController.java
No
Feature
Matpower files cannot be imported
Matpower files can be imported
No
> Matpower support

- diagram-viewer/pom.xml
Dependency update
powsybl-dependencies version is 2024.1.0
powsybl-dependencies version is 2024.2.0
> Update to powsybl-dependencies 2024.2.0

- diagram-viewer/pom.xml
- diagram-viewer/src/main/java/com/powsybl/diagram/viewer/common/AbstractDiagramController.java
- diagram-viewer/src/main/java/com/powsybl/diagram/viewer/nad/NetworkAreaDiagramController.java
- diagram-viewer/src/main/java/com/powsybl/diagram/viewer/sld/SingleLineDiagramController.java
- diagram-viewer/src/main/java/com/powsybl/diagram/viewer/sld/SingleLineDiagramModel.java
- diagram-viewer/src/main/java/com/powsybl/diagram/viewer/sld/SingleLineDiagramViewController.java
- diagram-viewer/src/main/java/com/powsybl/diagram/viewer/sld/SvgParametersBean.java
- diagram-viewer/src/main/resources/sld/view.fxml
No
Libs update
powsybl-dependencies 2024.2.0
powsybl-dependencies 2024.3.1
> Bump powsybl-dependencies to 2024.3.1

- scripts/get_message_templates.sh
- scripts/get_report_node.sh
No
Bug fix
**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**
The final report of "get_message_template.sh" process the dictionary file, but it is not yet generated.
- The final report of "get_message_template.sh" process the temporary file which will be use to generate the dictionary file.
- This PR also add an argument number check + display the usage when the check fails.
**If yes, please check if the following …
> Fix "get_message_template.sh" final report + check parameter count
